version: '3.8'

services:
  db:
    image: postgres:15
    container_name: scheduler-db
    restart: always
    environment:
      POSTGRES_USER: scheduler_user
      POSTGRES_PASSWORD: scheduler_pass
      POSTGRES_DB: scheduler_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
